# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: ramnisanth
# "service" is the name of this project. This will also be added to your AWS resource names.
service: Lambda-Function

provider:
  name: aws
  runtime: python3.12
  deploymentBucket:
    name: ram-nisanth-serverless

functions:
  lambda_function:
    handler: handler.lambda_function
    events:
      - httpApi:
          path: /
          method: get
package:
  individually: true
  include:
    - Lambda-Function-dev-lambda_function.zip
  exclude:
    - Lambda-Function
    - .serverless/**
    - .git/**
    - .github/**
    - "*.md"
    - serverless.yml
    
    
